# Introduction to Tensors

In [1]:
import tensorflow as tf
import numpy as np

Tensors are multi-dimensional arrays with a uniform type (called a `dtype`).  You can see all supported `dtypes` at `tf.dtypes.DType`.

If you're familiar with [NumPy](https://dphi.tech/lms/learn/introduction-to-numpy), tensors are (kind of) like `np.arrays`.

All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.


## Basics

Before creating basic tensors, let's understand some basics. 

### **Scalar, Vector, Matrix 101**


![image name](https://dphi-courses.s3.ap-south-1.amazonaws.com/tensor.jpeg)

* A scalar is a single number
* A vector is an array of numbers.
* A matrix is a 2-D array
* A tensor is a n-dimensional array with n >2



###  **Understanding Dimension - Indexes - Rank - Axes - Shape**

1.   List item
2.   List item



####**Dimension:** 

Let’s take an example of box to explain this. A simple box can have three dimensions width, length and depth (or height). Similarly, in data science we will be working “N” dimensional datasets. “N” could be any number.


![image name](https://dphi-courses.s3.ap-south-1.amazonaws.com/introduction-to-numpy/dimensions.png)




####**Indexes:** 

Indexes are required to access an element in a Data Structure.

![image name](https://dphi-courses.s3.ap-south-1.amazonaws.com/introduction-to-numpy/index+humans+and+python.png)

For example, suppose we have this array:

In [2]:
a = [1,2,3,4]

Now, suppose we want to access (refer to) the number 3 in this data structure. We can do it using a single index like so:


In [3]:
a[2]

3

In [4]:
#As another example, suppose we have this 2d-array:
 
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
] 

Now, suppose we want to access (refer to) the number 3 in this data structure. In this case, we need two indexes to locate the specific element.

In [5]:
dd[0][2]

3




#### **Rank:**


The rank of a tensor refers to the number of dimensions present within the tensor.


**Rank & Indexes:**

The rank of a tensor tells us how many indexes are required to access (refer to) a specific data element contained within the tensor data structure.

A tensor's rank tells us how many indexes are needed to refer to a specific element within the tensor.

####**Tensor Axes Example**
Let's look at some examples to make this solid. We'll consider the same tensor dd as before:

In [6]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]

Each element along the first axis, is an array:

In [7]:
dd[0]

[1, 2, 3]

In [8]:
dd[1]

[4, 5, 6]

In [9]:
dd[2]

[7, 8, 9]

Each element along the second axis, is a number:

In [10]:
dd[0][0]

1

In [11]:
dd[1][0]

4

In [12]:
dd[2][0]

7

In [13]:
dd[0][1]

2

In [14]:
dd[1][1]

5

In [15]:
dd[2][1]

8

In [16]:
dd[0][2]

3

In [17]:
dd[1][2]

6

In [18]:
dd[2][2]

9

Note that, with tensors, the elements of the last axis are always numbers. Every other axis will contain n-dimensional arrays. This is what we see in this example, but this idea generalizes.

The rank of a tensor tells us how many axes a tensor has, and the length of these axes leads us to the very important concept known as the shape of a tensor.

### **Shape of a Tensor**

The shape of a tensor is determined by the length of each axis, so if we know the shape of a given tensor, then we know the length of each axis, and this tells us how many indexes are available along each axis.

The shape of a tensor gives us the length of each axis of the tensor.
Let’s consider the same tensor dd as before:

In [19]:
# Let's say we have a 2D array
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]


In [20]:
#To work with this tensor's shape, we’ll create a tensor object like so:

t = tf.constant(dd)      # constant() is a function that helps you create a constant tensor
t

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [21]:
type(t)   # To get the type of object t

tensorflow.python.framework.ops.EagerTensor

In [22]:
# Now, we have a Tensor object, and so we can ask to see the tensor's shape:

t.shape

TensorShape([3, 3])

# Tensor Operation Types
Before we dive in with specific tensor operations, let’s get a quick overview of the landscape by looking at the main operation categories that encompass the operations we’ll cover. We have the following high-level categories of operations:

1. Reshaping operations
2. Element-wise operations
3. Reduction operations
4. Access operations

## Reshaping A Tensor In TensorFlow
Let’s look now at all the ways in which this tensor t can be reshaped without changing the rank:

Suppose that we have the following tensor:

In [23]:
t = tf.constant([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=tf.float32)    # can also mention the type of the element we want in the tensor

In [24]:
reshaped_tensor = tf.reshape(t, [1,12])     # reshape is a function that helps to reshaping any ndarray or ndtensor
print(reshaped_tensor)

tf.Tensor([[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]], shape=(1, 12), dtype=float32)


In [25]:
reshaped_tensor = tf.reshape(t, [2,6])
print(reshaped_tensor)

tf.Tensor(
[[1. 1. 1. 1. 2. 2.]
 [2. 2. 3. 3. 3. 3.]], shape=(2, 6), dtype=float32)


In [26]:
reshaped_tensor = tf.reshape(t, [3,4])
print(reshaped_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]], shape=(3, 4), dtype=float32)


Using the `reshape()` function, we can specify the `row x column` shape that we are seeking. Notice how all of the shapes have to account for the number of elements in the tensor. In our example this is:



```
rows * columns = 12 elements
```



We can use the intuitive words rows and columns when we are dealing with a rank 2 tensor. The underlying logic is the same for higher dimensional tenors even though we may not be able to use the intuition of rows and columns in higher dimensional spaces. For example:

In [27]:
reshaped_tensor = tf.reshape(t, [2,2,3])
print(reshaped_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 2. 2.]]

 [[2. 2. 3.]
  [3. 3. 3.]]], shape=(2, 2, 3), dtype=float32)


In this example, we increase the rank to 3, and so we lose the rows and columns concept. However, the product of the shape's components (2,2,3) still has to be equal to the number of elements in the original tensor ( 12).

## Changing Shape By Squeezing And Unsqueezing
The next way we can change the shape of our tensors is by squeezing and unsqueezing them.

1. Squeezing a tensor removes the dimensions or axes that have a length of one.
2. Unsqueezing a tensor adds a dimension with a length of one.

These functions allow us to expand or shrink the rank (number of dimensions) of our tensor. Let’s see this in action.

In [28]:
print(tf.reshape(t, [1,12]))

tf.Tensor([[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]], shape=(1, 12), dtype=float32)


In [29]:
print(tf.reshape(t, [1,12]).shape)

(1, 12)


In [30]:
print(tf.squeeze(tf.reshape(t, [1,12])))

tf.Tensor([1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.], shape=(12,), dtype=float32)


In [31]:
print(tf.squeeze(tf.reshape(t, [1,12])).shape)

(12,)



Let’s look at a common use case for squeezing a tensor by building a flatten function.

## Flatten A Tensor
A flatten operation on a tensor reshapes the tensor to have a shape that is equal to the number of elements contained in the tensor. This is the same thing as a 1d-array of elements.



```
Flattening a tensor means to remove all of the dimensions except for one.
```



Let’s create a Python function called `flatten()`:

In [32]:
def flatten(t):
    t = tf.reshape(t, [1, -1])
    t = tf.squeeze(t)
    return t

The flatten() function takes in a tensor t as an argument.

Since the argument t can be any tensor, we pass -1 as the second argument to the reshape() function. In TensorFlow, the -1 tells the reshape() function to figure out what the value should be based on the number of elements contained within the tensor. Remember, the shape must equal the product of the shape's component values. This is how TensorFlow can figure out what the value should be, given a 1 as the first argument.

Since our tensor t has 12 elements, the reshape() function is able to figure out that a 12 is required for the length of the second axis.

After squeezing, the first axis (axis-0) is removed, and we obtain our desired result, a 1d-array of length 12.

Here's an example of this in action:

In [33]:
t = tf.ones([4, 3])
t

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [34]:
flatten(t)

<tf.Tensor: shape=(12,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

## Concatenating Tensors
We combine tensors using the `concat()` function, and the resulting tensor will have a shape that depends on the shape of the two input tensors.

Suppose we have two tensors:

In [35]:
t1 = tf.constant([
    [1,2],
    [3,4]
])

t2 = tf.constant([
    [5,6],
    [7,8]
])

We can combine t1 and t2 row-wise (axis-0) in the following way:

In [36]:
tf.concat((t1, t2), axis = 0)  # concat() helps you to concatenate two tensors according to the given axis

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

We can combine them column-wise (axis-1) like this:

In [37]:
tf.concat((t1, t2), axis = 1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 5, 6],
       [3, 4, 7, 8]], dtype=int32)>

When we concatenate tensors, we increase the number of elements contained within the resulting tensor. This causes the component values within the shape (lengths of the axes) to adjust to account for the additional elements.

In [38]:
tf.concat((t1, t2), axis = 0).shape

TensorShape([4, 2])

In [39]:
tf.concat((t1, t2), axis = 1).shape

TensorShape([2, 4])

# Conclusion About Reshaping Tensors
We should now have a good understanding of what it means to reshape a tensor. Any time we change a tensor's shape, we are said to be reshaping the tensor.

Reference: Deeplizard